feat: A new feature
crowdin/crowdin-api-client-js pull request #326
Opened 2023-11-04 02:48 UTC by kisharnath

2023-11-13 09:12 UTC, andrii-bodnar commented on src/projectsGroups/index.ts
> +     * @param projectId
missing description and the second parameter

2023-11-13 09:13 UTC, andrii-bodnar commented on src/projectsGroups/index.ts
> +     * @param systemStringsExporterSettingsId
Please add descriptions and check the other annotations.

2023-11-13 09:13 UTC, andrii-bodnar commented on src/projectsGroups/index.ts
> +    export type StringSettings =
```suggestion
    export type StringExporterSettings =
```

2023-11-13 09:14 UTC, andrii-bodnar commented on src/projectsGroups/index.ts
> +     * @see https://developer.crowdin.com/api/v2/#operation/api.projects.file-format-settings.patch
wrong link

2023-11-13 15:08 UTC, kisharnath commented
please check now

2023-11-13 16:58 UTC, andrii-bodnar requested changes

2023-11-13 16:58 UTC, andrii-bodnar commented on src/projectsGroups/index.ts
> +    listProjectStringExporterSettings(
```suggestion
    listProjectStringsExporterSettings(
```


make it plural here and below (ProjectString**s**ExporterSettings)

2023-11-14 07:15 UTC, andrii-bodnar commented on src/projectsGroups/index.ts
> +    listProjectStringExporterSettings(
@kisharnath including the other methods, types and interfaces

2023-11-15 07:05 UTC, andrii-bodnar requested changes

2023-11-15 07:05 UTC, andrii-bodnar commented on src/projectsGroups/index.ts
> +     * @param projectId
```suggestion
     * @param projectId project identifier
```

2023-11-15 07:27 UTC, andrii-bodnar approved these changes
@kisharnath thank you!

2023-11-15 07:29 UTC, merged